### PR TITLE
Use InputStreamReader

### PR DESCRIPTION
**Pull request by RoboMWM**
1.12 removed the deprecated API you were suppressing.

### CODE REVIEW

**Comment by Camouflage100** [comment]
Prison v2 is no longer in developer and we are no longer releasing patches or releases for it.

**Comment by RoboMWM** [comment]
From your releases:

> Prison 2 will still remain in a bug-fix only mode up until the end of support date (which is a week after the Prison 3 initial release).

**Comment by Camouflage100** [comment]
That was before the entire Prison team resigned and left me as the only developer.

**Comment by RoboMWM** [comment]
Well, you could still accept PRs, you don't necessarily have to make formal releases but mk

**Pull request merged**
